name: icepyx-env

channels:
  - conda-forge

dependencies:
  - python=3.11
  - icepyx=1.3.0
  - geopandas=0.14.4
  - matplotlib=3.9.2
  - numpy=1.26.2
  - folium=0.18.0
  - branca=0.7.2
  - mapclassify=2.8.1
  # Do not pin external dependencies
  - jupyterlab
  - jupytext
